name: 🚀 CI/CD Streamlit → Cloud Run

on:
  push:
    branches: [main]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Install gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          export_default_credentials: true

      # 4️⃣ (Optional) Debug
      - name: Debug SERVICE_NAME
        run: echo "Deploying → $SERVICE_NAME in $GCP_PROJECT_ID/$GCP_REGION"

      # 5️⃣ Deploy via Buildpacks
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --source . \
            --region "$GCP_REGION" \
            --platform managed \
            --allow-unauthenticated \
            --quiet
